### ISSUE TITLE
Thread issue when scaling 

### ISSUE THREAD

**Issue by sushilks** [sushilks/mScale#25]
When scaling beyond 10k client (Right around 11k clients) Got the following error f

INFO 2016-03-15 06:37:47,359 zmq_sub.py:run:44 JOB RUN : ['./hydra', '10.10.0.223', '15556']
INFO 2016-03-15 06:37:47,371 hdaemon.py:**init**:16 initiated..., REP port[33217]
INFO 2016-03-15 06:37:47,371 hdaemon.py:run:29 spawning run thread...
Traceback (most recent call last):
  File "./hydra", line 27, in <module>
    exit(iFunc(argv))
  File "../python/hydra/zmqtest/zmq_sub.py", line 57, in run
    hd.run()
  File "../python/hydra/lib/hdaemon.py", line 31, in run
    self.h_threading.start_thread(self.thread_cb, self.start)
  File "../python/hydra/lib/utility/h_threading.py", line 51, in start_thread
    t._start_thread(callback_fn, fn, daemon, **kwargs)
  File "../python/hydra/lib/utility/h_threading.py", line 25, in _start_thread
    self.thread.start()
  File "/usr/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread

**Comment by sushilks** [comment]
This has not been seen for a while, it was likely due to memory running out. 
After reducing form 10k to 8k clients the problem does not show up. 
for 10k client additional slaves will be needed.
